#!/bin/sh
#

# PROVIDE: finance

. /etc/rc.subr

name="finance"
rcvar="${name}_enable"
pidfile="/var/run/${name}.pid"
command="/usr/sbin/daemon"
command_args="-c -f -P ${pidfile} -r /home/robert/finance/api_build/index.js"

load_rc_config $name
run_rc_command "$1"
